<a href="https://colab.research.google.com/github/Zeke-Woods/Linear_Algebra_Coding_Projects/blob/main/Determinant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load Numpy and Other Stuff

Run both


In [ ]:
#@title
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
#@title
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)
    
    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A   


def is_singular(matrix):
  singular = True
  notsingular = False

  (mr, mc) = matrix.shape
  
  return_value = notsingular
  if (mc - np.linalg.linalg.matrix_rank(matrix) > 0) :
    return_value = singular
  return return_value
 
    
    

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


**ONLY LOAD THE MATRICES YOU WANT TO CALCULATE**

or make new matrices and only load them*

In [ ]:
#  2x2's:

A = np.matrix([[10, 7],
               [8, 9]])

B = np.matrix([[-10, -1],
               [-4, 7]])

C = np.matrix([[1, -3],
               [7, 7]])


In [ ]:
#@title
#3x3's

A = np.matrix([[ 3,   2,  3],
               [-6,  1, -10],
               [-8, -9,  -9]])

B = np.matrix([[1, -2,  1],
               [5,  5,  4],
               [4,  0,  0]])

C = np.matrix([[1,   0,   0],
               [0,   2,   0],
               [-3, -2,   1]])

Run all the calculations below after choosing a set of Matrices

In [ ]:
#@title
# Finds all the Determinants by themselves
print(" Det of A: ", "\n",  np.round(np.linalg.det(A), decimals = 5, out = None), "\n")
print(" Det of B: ", "\n",  np.round(np.linalg.det(B), decimals = 5, out = None), "\n")
print(" Det of C: ", "\n",  np.round(np.linalg.det(C), decimals = 5, out = None), "\n")

 Det of A:  
 -59.0 

 Det of B:  
 -52.0 

 Det of C:  
 2.0 



In [ ]:
#@title
# gives both A * B and B * A then the Determanent of A * B and B * A
print(" A * B is: ", "\n", A*B, "\n")
print(" Det of A * B: ", "\n",  np.round(np.linalg.det(A * B), decimals = 5, out = None), "\n")

print(" B * A is: ", "\n", B*A, "\n")
print(" Det of B * A: ", "\n",  np.round(np.linalg.det(B * A), decimals = 5, out = None), "\n")

 A * B is:  
 [[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]] 

 Det of A * B:  
 3068.0 

 B * A is:  
 [[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]] 

 Det of B * A:  
 3068.0 



In [ ]:
#@title
# gives both A * C and C * A then the Determanent of A * C and C * A
print(" A * C is: ", "\n", A*C, "\n")
print(" Det of A * C: ", "\n",  np.round(np.linalg.det(A * C), decimals = 5, out = None), "\n")

print(" C * A is: ", "\n", C*A, "\n")
print(" Det of C * A: ", "\n",  np.round(np.linalg.det(C * A), decimals = 5, out = None), "\n")

 A * C is:  
 [[ -6  -2   3]
 [ 24  22 -10]
 [ 19   0  -9]] 

 Det of A * C:  
 -118.0 

 C * A is:  
 [[  3   2   3]
 [-12   2 -20]
 [ -5 -17   2]] 

 Det of C * A:  
 -118.0 



In [ ]:
#@title
# gives both B * C and C * B then the Determanent of B * C and C * B
print(" B * C is: ", "\n", B*C, "\n")
print(" Det of B * C: ", "\n",  np.round(np.linalg.det(B * C), decimals = 5, out = None), "\n")

print(" C * B is: ", "\n", C*B, "\n")
print(" Det of C * B: ", "\n",  np.round(np.linalg.det(C * B), decimals = 5, out = None), "\n")

 B * C is:  
 [[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]] 

 Det of B * C:  
 -104.0 

 C * B is:  
 [[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]] 

 Det of C * B:  
 -104.0 

