<a href="https://colab.research.google.com/github/Zeke-Woods/Linear_Algebra_Coding_Projects/blob/main/LinAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"


In [2]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)
    
    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A   


def is_singular(matrix):
  singular = True
  notsingular = False

  (mr, mc) = matrix.shape
  
  return_value = notsingular
  if (mc - np.linalg.linalg.matrix_rank(matrix) > 0) :
    return_value = singular
  return return_value
 
    
    

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


In [3]:
# create a vector
M = np.matrix([[1],
              [2],
              [3],
              [4]])
print(M) 

[[1]
 [2]
 [3]
 [4]]


In [4]:
r = np.matrix('1; 2; 3; 4')
r

matrix([[1],
        [2],
        [3],
        [4]])

In [5]:
#use an array instead
a = np.array([0, 2, -4, 4])
a

array([ 0,  2, -4,  4])

In [6]:
np.sqrt(a.dot(a))


6.0

this is a text block... also: 



Using the Gram-Scmidt Orthonormalization Process


In [15]:
#the messy vectors
r1 = np.array([ 0,2,-4,4])
r2 = np.array([0,2,-2,6])
r3 = np.array([0,0,-7,11])
r4 = np.array([1,2,3,4])

In [8]:
#Find the first nice basis vector:
t1 = r1
#subtract off the nice basis vectors:
#Nothing yet

# Find the magnitude of t1:
n1 = np.sqrt(t1.dot(t1))

# So, u1 = (1/n1) * t1
u1 = (1/n1) * t1

print(n1)

u1

6.0


array([ 0.        ,  0.33333333, -0.66666667,  0.66666667])

In [9]:
# Verify that u1 has size 1 and is orthogonal to all other u vectors
np.sqrt(u1.dot(u1))

0.9999999999999999

In [10]:
#Find the second nice basis vector:
t2 = r2 - r2.dot(u1) * u1

#subtract off the nice basis vectors:
#Nothing yet

# Find the magnitude of t1:
n2 = np.sqrt(t2.dot(t2))

# So, u2 = (1/n2) * t2
u2 = (1/n2) * t2

print(n2)

u2

2.8284271247461903


array([0.        , 0.        , 0.70710678, 0.70710678])

In [11]:
# Verify that u2 has size 1 and is orthogonal to all other u vectors
print("The size of u2 = ", np.sqrt(u2.dot(u2)))
print("u2 . u1 = ", u2.dot(u1))

The size of u2 =  0.9999999999999999
u2 . u1 =  -7.66449056764364e-18


In [12]:
#Find the third nice basis vector:
t3 = r3 - r3.dot(u1) * u1 - r3.dot(u2) * u2

#subtract off the nice basis vectors:
#Nothing yet

# Find the magnitude of t1:
n3 = np.sqrt(t3.dot(t3))

# So, u3 = (1/n3) * t3
u3 = (1/n3) * t3

print(n3)

u3

4.242640687119285


array([ 0.        , -0.94280904, -0.23570226,  0.23570226])

In [13]:
# Verify that u3 has size 1 and is orthogonal to all other u vectors
print("The size of u3 = ", np.sqrt(u3.dot(u3)))
print("u3 . u2 = ", np.round(u3.dot(u2), decimals=8, out=None))
print("u3 . u1 = ", np.round(u3.dot(u1), decimals=8, out=None))

The size of u3 =  1.0
u3 . u2 =  0.0
u3 . u1 =  0.0


In [16]:
#Find the fourth nice basis vector:
t4 = r4 - r4.dot(u1) * u1 - r4.dot(u2) * u2 - r4.dot(u3) * u3

#subtract off the nice basis vectors:
#Nothing yet

# Find the magnitude of t1:
n4 = np.sqrt(t4.dot(t4))

# So, u2 = (1/n2) * t2
u4 = (1/n4) * t4

print(n4)

u4

1.0


array([1.00000000e+00, 6.66133815e-16, 2.22044605e-16, 1.55431223e-15])

In [17]:
# Verify that u4 has size 1 and is orthogonal to all other u vectors
print("The size of u4 = ", np.sqrt(u4.dot(u4)))
print("u4 . u3 = ", np.round(u4.dot(u3), decimals=8, out=None))
print("u4 . u2 = ", np.round(u4.dot(u2), decimals=8, out=None))
print("u4 . u1 = ", np.round(u4.dot(u1), decimals=8, out=None))

The size of u4 =  1.0
u4 . u3 =  -0.0
u4 . u2 =  0.0
u4 . u1 =  0.0
